"""spotify_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SUApf6zkQfQZDmHNB-2nVfBmqUJcxhp-
"""

#Install kaggle
!pip install kaggle

#Upload kaggle.json
from google.colab import files
files.upload()   # A button will appear → click it → select kaggle.json

#Set up kaggle credentials
import os
os.makedirs('/root/.kaggle', exist_ok=True)
!cp kaggle.json /root/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json
print("Kaggle setup done!")

#Download dataset
!kaggle datasets download -d zaheenhamidani/ultimate-spotify-tracks-db
!unzip ultimate-spotify-tracks-db.zip
!ls   # This shows you the files — look for the .csv file name

#Load data and explore
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

#Load the CSV
df = pd.read_csv('SpotifyFeatures.csv')

print("Shape:", df.shape)
print("\nFirst 5 rows:")
df.head()

#Data Cleaning
print("=== MISSING VALUES ===")
print(df.isnull().sum())

print("\n=== DATA TYPES ===")
print(df.dtypes)

#Drop rows with missing values in our feature columns
features_needed = ['danceability', 'energy', 'tempo', 'loudness', 'valence']

#Check if columns exist
df.columns = df.columns.str.lower().str.strip()
print("\n=== ALL COLUMNS ===")
print(df.columns.tolist())

#Select features and clean
features = ['danceability', 'energy', 'tempo', 'loudness', 'valence']

#Keep only rows where these columns have values
df_clean = df[features].dropna()

print(f"Original rows: {len(df)}")
print(f"After removing missing: {len(df_clean)}")
print("\nStats:")
df_clean.describe()

#Encoding categorical columns (genre)
from sklearn.preprocessing import LabelEncoder

#Check if genre column exists
if 'genre' in df.columns:
    le = LabelEncoder()
    df['genre_encoded'] = le.fit_transform(df['genre'].astype(str))
    print("Genre encoding done!")
    print(df['genre'].value_counts().head(10))
else:
    print("No genre column found, skipping encoding")

#Also keep track of song names if available
if 'track_name' in df.columns:
    df_names = df[['track_name'] + features].dropna()
else:
    df_names = df_clean.copy()

# CELL 9 — Normalize features (make all values between 0 and 1)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_clean)

print("Normalization done!")
print("Shape of scaled data:", X_scaled.shape)
print("\nFirst row sample:", X_scaled[0])

#Elbow method to find best K
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

inertia = []
K_range = range(2, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 4))
plt.plot(K_range, inertia, 'bo-', linewidth=2, markersize=8)
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia')
plt.title('Elbow Method — Finding Best K')
plt.grid(True)
plt.tight_layout()
plt.savefig('elbow_plot.png')
plt.show()
print("Best K is where the 'elbow' bends — usually around 4-6")

#Apply KMeans with chosen K
best_k = 5  # Change this based on elbow plot

kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)
df_clean['cluster'] = kmeans.fit_predict(X_scaled)

print(f"Clustering done with K={best_k}")
print("\nSongs per cluster:")
print(df_clean['cluster'].value_counts().sort_index())

#PCA Visualization (2D)
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(10, 6))
colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7']
for i in range(best_k):
    mask = df_clean['cluster'] == i
    plt.scatter(X_pca[mask, 0], X_pca[mask, 1],
                c=colors[i % len(colors)], label=f'Cluster {i}',
                alpha=0.6, s=10)

plt.title('🎵 Spotify Songs Clustered — PCA View')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.legend()
plt.tight_layout()
plt.savefig('pca_plot.png')
plt.show()

#t-SNE Visualization
from sklearn.manifold import TSNE

#Use a sample for speed (t-SNE is slow on large data)
sample_size = min(3000, len(X_scaled))
idx = np.random.choice(len(X_scaled), sample_size, replace=False)
X_sample = X_scaled[idx]
labels_sample = df_clean['cluster'].values[idx]

tsne = TSNE(n_components=2, random_state=42, perplexity=30)
X_tsne = tsne.fit_transform(X_sample)

plt.figure(figsize=(10, 6))
for i in range(best_k):
    mask = labels_sample == i
    plt.scatter(X_tsne[mask, 0], X_tsne[mask, 1],
                c=colors[i % len(colors)], label=f'Cluster {i}',
                alpha=0.6, s=10)

plt.title('🎵 Spotify Songs Clustered — t-SNE View')
plt.xlabel('t-SNE 1')
plt.ylabel('t-SNE 2')
plt.legend()
plt.tight_layout()
plt.savefig('tsne_plot.png')
plt.show()

#Show average values per cluster
cluster_means = df_clean.groupby('cluster')[features].mean()
print("Average feature values per cluster:")
print(cluster_means.round(3))

#Plot
cluster_means.plot(kind='bar', figsize=(12, 5), colormap='Set2')
plt.title('Average Audio Features per Cluster')
plt.xlabel('Cluster')
plt.ylabel('Normalized Value')
plt.xticks(rotation=0)
plt.legend(loc='upper right')
plt.tight_layout()
plt.savefig('cluster_features.png')
plt.show()

#Save model and data for Streamlit app
import pickle

#Save the model and scaler
with open('kmeans_model.pkl', 'wb') as f:
    pickle.dump(kmeans, f)

with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

#Save cleaned data with clusters
df_clean.to_csv('clustered_songs.csv', index=False)

print("Saved: kmeans_model.pkl, scaler.pkl, clustered_songs.csv")
print("Also saved images: elbow_plot.png, pca_plot.png, tsne_plot.png, cluster_features.png")

#Download all files to your computer
from google.colab import files

files.download('kmeans_model.pkl')
files.download('scaler.pkl')
files.download('clustered_songs.csv')
files.download('elbow_plot.png')
files.download('pca_plot.png')
files.download('tsne_plot.png')
files.download('cluster_features.png')

print("All files downloaded!")

